server {
    listen 80;
    server_name localhost;

    # Static Files (CSS/JS)
    location /static/ {
        alias /app/static/;
    }

    # Media Files
    location /media/ {
        alias /app/media/;
    }

    #  Dynamic API & Page Requests (Django/Gunicorn Forward)
    location / {
        proxy_pass http://django-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}