apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infraflow-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Shivam-015/Infraflow.git' 
    targetRevision: HEAD
    path: kubernetes                    
    directory:
      recurse: true                    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infraflow
  syncPolicy:
    automated:
      prune: true                      
      selfHeal: true                    
    syncOptions:
      - CreateNamespace=true     