apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: infraflow
data:
  DB_HOST: "mysql-service"   
  DB_NAME: "ecommercedb"      
  DB_USER: "admin"           
  DB_PORT: "3306" 
  DEBUG: "True" 

---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: infraflow
  
type: Opaque
stringData:
  DB_USER: "root"
  DB_PASSWORD: "rootpassword" 
  SECRET_KEY: 'django-insecure-bih5p!sw90hayvq&ntxaqvfb)ir=25k=+2y&au=g^*j+i1ha41'