namespace: infraflow

django:
  replicaCount: 2
  image:
    repository: shivamgupta51/infraflow-app
    tag: latest
    pullPolicy: Always
  service:
    port: 8000
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  config:
    dbHost: "mysql-service"
    dbName: "ecommercedb"
    dbPort: "3306"
    debug: "True"

mysql:
  replicaCount: 1
  image:
    repository: mysql
    tag: "8.4"
  storage: 1Gi

nginx:
  replicaCount: 1
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    port: 80
    nodePort: 30080
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"

ingress:
  host: infraflow.local